#!/usr/bin/env bash

function teamcity_server {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default|agent|teamcity)
      perl -pe 's{^(\s*)("\$JRE_HOME/bin/java")}{$1 exec $2} if m{jetbrains.buildServer.agent.Launcher}' -i "$shome/vendor/teamcity-10.0-agent/bin/agent.sh"
      exec "$shome/vendor/teamcity-10.0-agent/bin/agent.sh" run
      ;;
    server)
      perl -pe 's{^(\s*)(\./catalina.sh)}{$1 exec $2}' -i "$shome/vendor/teamcity-10.0/TeamCity/bin/teamcity-server.sh"
      exec "$shome/vendor/teamcity-10.0/TeamCity/bin/teamcity-server.sh" run
      ;;
     *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

teamcity_server "$@"
